import { Platform, StyleSheet } from 'react-native';

const DR = {
  panel: 14,
  block: 12,
  soft: 10,
  chip: 8,
  mini: 6,
};

export function createAppStyles(C) {
  return StyleSheet.create({
  appShell: { flex: 1 },
  appUnderlay: { flex: 1 },
  splashOverlay: { ...StyleSheet.absoluteFillObject, zIndex: 100 },
  safeRoot: { flex: 1, backgroundColor: C.appBg },
  root: { flex: 1, backgroundColor: C.appBg },
  scrollContent: { paddingBottom: 0, backgroundColor: C.appBg },
  row: { flexDirection: 'row', alignItems: 'center' },
  header: {
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
    backgroundColor: C.headerBg,
  },
  headerTopRow: { justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 12 },
  stackCol: { flexDirection: 'column', alignItems: 'stretch' },
  headerStackGap: { gap: 6 },
  brandStack: { alignItems: 'flex-start' },
  hdrCenter: { alignItems: 'center', gap: 2 },
  xauRow: { alignItems: 'baseline', gap: 8 },
  xauPair: { fontSize: 8, color: C.dim, letterSpacing: 2, fontWeight: '600' },
  xauPrice: { fontSize: 28, fontWeight: '800', color: C.goldL },
  xauChg: { fontSize: 12, fontWeight: '700' },
  xauSub: { fontSize: 8, color: C.dim, letterSpacing: 1 },
  headerNotes: {
    marginTop: 5,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 2,
    paddingHorizontal: 10,
    paddingVertical: Platform.OS === 'ios' ? 7 : 5,
    color: C.text,
    fontSize: 10,
    backgroundColor: C.inputBg,
  },
  hdrRight: { gap: 14 },
  uiLayoutBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: 10,
    paddingVertical: 8,
    borderTopWidth: 1,
    borderTopColor: C.border,
    marginHorizontal: -1,
    backgroundColor: C.panel,
  },
  uiLayoutLbl: { fontSize: 10, fontWeight: '700', color: C.dim, letterSpacing: 0.8 },
  uiLayoutLblOn: { color: C.goldL },
  uiLayoutSwitchRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  livePill: {
    borderWidth: 1,
    borderColor: 'rgba(0,230,118,0.3)',
    backgroundColor: 'rgba(0,230,118,0.04)',
    paddingVertical: 5,
    paddingHorizontal: 11,
    borderRadius: 20,
    gap: 6,
  },
  livePillTxt: { fontSize: 8, color: C.green, letterSpacing: 2, fontWeight: '700' },
  ldot: { width: 6, height: 6, borderRadius: 3 },
  clockBox: { alignItems: 'flex-end' },
  clockUtc: { fontSize: 16, fontWeight: '800', color: C.gold },
  clockEst: { fontSize: 8, color: C.dim, letterSpacing: 1, marginTop: 1, fontWeight: '500' },

  bannerScroll: { maxHeight: 52, borderBottomWidth: 1, borderBottomColor: 'rgba(255,61,87,0.2)', backgroundColor: C.appBg },
  godBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    paddingVertical: 10,
    backgroundColor: 'rgba(255,61,87,0.04)',
  },
  gmAlert: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  gmAlertTxt: { fontSize: 9, letterSpacing: 1.5, fontWeight: '700' },
  gmDivider: { width: 1, height: 16, backgroundColor: C.border },

  sessBar: { flexDirection: 'row', flexWrap: 'wrap', borderBottomWidth: 1, borderBottomColor: C.border, backgroundColor: C.panel },
  sblk: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 9,
    paddingHorizontal: 16,
    borderRightWidth: 1,
    borderRightColor: C.border,
    borderTopWidth: 2,
    borderTopColor: 'transparent',
  },
  sblkActive: { borderTopColor: C.gold, backgroundColor: 'rgba(201,168,76,0.04)' },
  sblkDead: { borderTopColor: 'rgba(255,61,87,0.4)', backgroundColor: 'rgba(255,61,87,0.02)' },
  sn: { fontSize: 8, color: C.dim, letterSpacing: 1.5, marginBottom: 2, fontWeight: '600' },
  st: { fontSize: 9, color: C.text, fontWeight: '500' },
  sbadge: { fontSize: 7, letterSpacing: 1, paddingVertical: 3, paddingHorizontal: 8, borderRadius: 10, overflow: 'hidden', fontWeight: '700' },
  sbOpen: { color: C.green, borderWidth: 1, borderColor: 'rgba(0,230,118,0.3)', backgroundColor: C.greenD },
  sbWait: { color: C.amber, borderWidth: 1, borderColor: 'rgba(255,179,0,0.3)', backgroundColor: 'rgba(255,179,0,0.05)' },
  sbDead: { color: C.red, borderWidth: 1, borderColor: 'rgba(255,61,87,0.3)', backgroundColor: C.redD },

  flowScroll: { borderBottomWidth: 1, borderBottomColor: C.border, backgroundColor: C.flowBg, maxHeight: 92 },
  btBar: {
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(212,180,90,0.25)',
    backgroundColor: C.btBarBg,
    paddingVertical: 8,
    gap: 6,
  },
  btBarTitle: { fontSize: 8, color: C.amber, letterSpacing: 1, fontWeight: '700' },
  btBarRow: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 8 },
  btBarMeta: { fontSize: 9, color: C.dim, flex: 1, textAlign: 'right' },
  btMiniBtn: {
    borderWidth: 1,
    borderColor: C.border,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 6,
    backgroundColor: 'rgba(14,12,10,0.5)',
  },
  btMiniBtnTxt: { fontSize: 12, color: C.goldL, fontWeight: '800' },
  btSlider: { width: '100%', height: 36 },
  flowWrap: { flexDirection: 'row', alignItems: 'center', gap: 2, paddingVertical: 10 },
  fnode: {
    alignItems: 'center',
    gap: 2,
    paddingVertical: 6,
    paddingHorizontal: 8,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.panel2,
    minWidth: 68,
    borderRadius: DR.soft,
  },
  fnodePass: { borderColor: 'rgba(0,230,118,0.35)', backgroundColor: 'rgba(0,230,118,0.04)' },
  fnodeFail: { borderColor: 'rgba(255,61,87,0.35)', backgroundColor: 'rgba(255,61,87,0.04)' },
  fnodeWarn: { borderColor: 'rgba(255,179,0,0.35)', backgroundColor: 'rgba(255,179,0,0.04)' },
  fi: { fontSize: 11 },
  fn: { fontSize: 6, color: C.dim, fontWeight: '600' },
  ft: { fontSize: 7, color: C.text, letterSpacing: 0.3, textAlign: 'center', lineHeight: 11, fontWeight: '600' },
  fnewTag: {
    fontSize: 6,
    color: C.gold,
    backgroundColor: 'rgba(201,168,76,0.1)',
    borderWidth: 1,
    borderColor: 'rgba(201,168,76,0.2)',
    paddingHorizontal: 4,
    paddingVertical: 1,
    borderRadius: DR.mini,
    marginTop: 1,
    fontWeight: '700',
  },
  farr: { fontSize: 10, color: C.dim2, paddingHorizontal: 1 },

  grid: { gap: 12, paddingVertical: 12 },
  col: { gap: 10 },
  leftCol: { gap: 10 },
  centerCol: { gap: 10 },
  rightCol: { gap: 10 },

  footer: {
    paddingTop: 8,
    paddingBottom: 4,
    borderTopWidth: 1,
    borderTopColor: C.border,
    backgroundColor: C.panel,
    gap: 6,
  },
  footerTxt: { fontSize: 7, color: C.dim, letterSpacing: 1, fontWeight: '500' },
  footerGold: { color: C.goldD, fontWeight: '700' },
  footerMinimal: { paddingTop: 6, paddingBottom: 4 },

  mobileCompactHdr: { paddingVertical: 10 },
  mobileTabBody: { paddingTop: 12, paddingBottom: 0, gap: 10 },

  bottomNavOuter: {
    paddingHorizontal: 0,
    paddingTop: 0,
  },
  bottomNavBar: {
    position: 'relative',
    borderRadius: 0,
    overflow: 'hidden',
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: 'rgba(212,180,90,0.18)',
    paddingTop: 4,
    paddingBottom: 2,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -2 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
      },
      android: { elevation: 6 },
      default: {},
    }),
  },
  bottomNavBarTint: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: Platform.OS === 'ios' ? 'rgba(18,16,12,0.78)' : 'rgba(18,16,12,0.96)',
  },
  bottomNavRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'stretch',
    paddingHorizontal: 2,
    paddingTop: 0,
    zIndex: 3,
  },
  bottomNavItem: {
    flex: 1,
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 6,
    minHeight: 50,
    borderRadius: 0,
    marginHorizontal: 0,
    minWidth: 0,
    backgroundColor: 'transparent',
  },
  bottomNavItemActive: {
    backgroundColor: 'rgba(212,180,90,0.07)',
  },
  bottomNavItemPressed: { opacity: 0.88 },
  bottomNavActiveCapWrap: {
    position: 'absolute',
    top: 2,
    left: 0,
    right: 0,
    alignItems: 'center',
    zIndex: 4,
  },
  bottomNavActiveCap: {
    width: 28,
    height: 2,
    borderRadius: 2,
    backgroundColor: C.goldL,
    opacity: 0.95,
  },
  bottomNavItemInner: { alignItems: 'center', justifyContent: 'center', gap: 2, paddingTop: 5 },
  bottomNavIcon: {
    fontSize: 28,
    color: 'rgba(233,224,200,0.45)',
    fontWeight: '600',
  },
  bottomNavIconActive: { color: C.goldL },
  bottomNavLbl: {
    fontSize: 8,
    fontWeight: '700',
    color: 'rgba(233,224,200,0.52)',
    letterSpacing: 0.9,
    textTransform: 'uppercase',
  },
  bottomNavLblActive: {
    color: C.goldL,
    fontWeight: '800',
    letterSpacing: 1,
  },

  psTabBody: { paddingTop: 8, paddingBottom: 0 },
  psScroll: { gap: 16, paddingTop: 4 },
  psProfileCard: {
    position: 'relative',
    borderRadius: 14,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(212,180,90,0.28)',
    paddingVertical: 20,
    paddingHorizontal: 16,
    alignItems: 'center',
  },
  psProfileTint: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(20,18,14,0.88)',
  },
  psProfileGlow: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: 4,
    backgroundColor: C.gold,
    opacity: 0.55,
    borderTopLeftRadius: 14,
    borderBottomLeftRadius: 14,
  },
  psAvatarRing: {
    width: 68,
    height: 68,
    borderRadius: 34,
    borderWidth: 3,
    borderColor: C.goldL,
    backgroundColor: 'rgba(0,0,0,0.35)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
    overflow: 'hidden',
    ...Platform.select({
      ios: {
        shadowColor: C.gold,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.45,
        shadowRadius: 8,
      },
      android: { elevation: 10 },
      default: {},
    }),
  },
  psAvatarTxt: { fontSize: 22, fontWeight: '900', color: C.goldL, letterSpacing: 1 },
  psAvatarImage: { width: '100%', height: '100%', borderRadius: 34 },
  psAvatarHint: { fontSize: 8, color: C.dim, textAlign: 'center', marginTop: 4, letterSpacing: 0.8 },
  psName: { fontSize: 20, fontWeight: '800', color: C.text, textAlign: 'center' },
  psNameHint: { fontSize: 8, color: C.dim, textAlign: 'center', marginTop: 4, letterSpacing: 1 },
  psNameInput: {
    marginTop: 4,
    marginBottom: 4,
    minWidth: 200,
    borderWidth: 1,
    borderColor: C.gold,
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 14,
    color: C.text,
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'center',
    backgroundColor: 'rgba(0,0,0,0.25)',
  },
  psBrokerInput: {
    marginTop: 8,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 12,
    color: C.text,
    fontSize: 11,
    backgroundColor: 'rgba(0,0,0,0.22)',
  },
  psTierBadge: {
    marginTop: 10,
    paddingVertical: 5,
    paddingHorizontal: 14,
    borderRadius: 20,
    borderWidth: 1,
    backgroundColor: 'rgba(0,0,0,0.2)',
  },
  psTierTxt: { fontSize: 9, fontWeight: '900', letterSpacing: 2 },
  psStatsRow: { flexDirection: 'row', gap: 8, marginTop: 16, alignSelf: 'stretch' },
  psStatGlass: {
    flex: 1,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(212,180,90,0.2)',
    backgroundColor: 'rgba(255,255,255,0.04)',
    paddingVertical: 10,
    paddingHorizontal: 6,
    alignItems: 'center',
    minHeight: 64,
    justifyContent: 'center',
  },
  psStatLbl: { fontSize: 6, color: C.dim, letterSpacing: 1.2, fontWeight: '700', marginBottom: 4 },
  psStatVal: { fontSize: 13, fontWeight: '900' },
  psSparkWrap: { marginTop: 14, alignSelf: 'stretch', alignItems: 'center', opacity: 0.95 },
  psSwitchProfileBtn: {
    marginTop: 16,
    minHeight: 48,
    paddingVertical: 12,
    paddingHorizontal: 22,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: C.gold,
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
  },
  psSwitchProfileTxt: { fontSize: 10, fontWeight: '800', color: C.goldL, letterSpacing: 2 },
  psDivider: {
    height: 1,
    backgroundColor: C.border,
    marginVertical: 4,
    opacity: 0.9,
  },
  psSettingsTitle: {
    fontSize: 10,
    fontWeight: '900',
    color: C.gold,
    letterSpacing: 3,
    marginTop: 4,
    marginBottom: 8,
  },
  psSettingsCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: 'rgba(0,0,0,0.18)',
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 0,
  },
  psRowLabel: { fontSize: 9, fontWeight: '800', color: C.dim, letterSpacing: 1.5, marginBottom: 8, marginTop: 4 },
  psSegRow: { flexDirection: 'row', gap: 6, marginBottom: 4 },
  psSegChip: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: 'rgba(255,255,255,0.03)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
    paddingHorizontal: 4,
  },
  psSegChipOn: {
    borderColor: 'rgba(212,180,90,0.65)',
    backgroundColor: 'rgba(212,180,90,0.14)',
  },
  psSegChipTxt: { fontSize: 9, fontWeight: '700', color: C.dim, textAlign: 'center' },
  psSegChipTxtOn: { color: C.goldL, fontWeight: '900' },
  psRowDivider: { height: 1, backgroundColor: 'rgba(30,23,0,0.55)', marginVertical: 12 },
  psToggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    minHeight: 48,
    paddingVertical: 6,
    gap: 12,
  },
  psToggleLbl: { fontSize: 11, fontWeight: '700', color: C.text, flex: 1 },
  psToggleHint: { fontSize: 9, color: C.dim, marginRight: 8, fontWeight: '600' },
  psResetBtn: {
    marginTop: 18,
    minHeight: 48,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(255,61,87,0.65)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    backgroundColor: 'rgba(255,61,87,0.06)',
  },
  psResetTxt: { fontSize: 10, fontWeight: '800', color: C.red, letterSpacing: 1.5 },
  psModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.72)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 22,
  },
  psModalCard: {
    width: '100%',
    maxWidth: 340,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(212,180,90,0.35)',
    backgroundColor: C.panel2,
    padding: 16,
    zIndex: 2,
  },
  psModalTitle: { fontSize: 11, fontWeight: '900', color: C.goldL, letterSpacing: 2, marginBottom: 12, textAlign: 'center' },
  psModalRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: C.border,
    marginBottom: 8,
    gap: 12,
    minHeight: 52,
  },
  psModalRowOn: { borderColor: C.gold, backgroundColor: 'rgba(212,180,90,0.1)' },
  psModalAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: C.goldL,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.3)',
    overflow: 'hidden',
  },
  psModalAvatarImg: { width: '100%', height: '100%' },
  psModalAvatarTxt: { fontSize: 12, fontWeight: '900', color: C.goldL },
  psModalName: { fontSize: 14, fontWeight: '800', color: C.text },
  psModalTier: { fontSize: 9, color: C.dim, marginTop: 2, letterSpacing: 1 },
  psModalCheck: { fontSize: 16, color: C.green, fontWeight: '900' },
  psModalClose: { marginTop: 8, paddingVertical: 12, alignItems: 'center' },
  psModalCloseTxt: { fontSize: 10, fontWeight: '800', color: C.dim, letterSpacing: 2 },

  ghBody: { paddingVertical: 0 },
  ghWrap: { position: 'relative', paddingBottom: 0 },
  ghPriceCard: {
    borderRadius: 16,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(201,168,76,0.35)',
  },
  ghPriceInner: { padding: 16, position: 'relative', zIndex: 1 },
  ghPriceMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 4,
  },
  ghPriceStatBlock: { flex: 1, alignItems: 'center', paddingHorizontal: 6 },
  ghPriceStatDivider: { width: 1, height: 44, backgroundColor: 'rgba(30,23,0,0.85)' },
  ghMiniLbl: { fontSize: 6, color: C.dim, letterSpacing: 1, fontWeight: '600' },
  ghMiniVal: { fontSize: 18, fontWeight: '800', marginTop: 4 },
  ghPriceFoot: {
    marginTop: 14,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: 'rgba(30,23,0,0.6)',
    justifyContent: 'space-between',
  },
  ghFootUtc: { fontSize: 8, color: C.dim2, fontWeight: '500' },
  ghFootEdge: { fontSize: 8, color: C.amber, fontWeight: '700', letterSpacing: 1, flex: 1, textAlign: 'right' },
  ghChipScroll: { maxHeight: 44, marginTop: 14 },
  ghChipRow: { gap: 8, alignItems: 'center', paddingVertical: 4 },
  ghChip: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(201,168,76,0.25)',
    backgroundColor: 'rgba(15,13,6,0.95)',
  },
  ghChipTxt: { fontSize: 7, fontWeight: '800', color: C.gold, letterSpacing: 1.2 },
  ghGrid2: { flexDirection: 'row', gap: 10, marginTop: 16 },
  ghStatTile: {
    flex: 1,
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.panel2,
  },
  ghStatLbl: { fontSize: 7, color: C.dim, letterSpacing: 2, fontWeight: '700', marginBottom: 6 },
  ghStatVal: { fontSize: 20, fontWeight: '900' },
  ghStatSub: { fontSize: 7, color: C.dim2, marginTop: 4, fontWeight: '500' },
  ghVerdictCard: {
    marginTop: 14,
    padding: 16,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: C.border,
    borderLeftWidth: 4,
    borderLeftColor: C.gold,
    backgroundColor: 'rgba(201,168,76,0.04)',
  },
  ghVerdictLbl: { fontSize: 7, color: C.dim, letterSpacing: 2, fontWeight: '800', marginBottom: 6 },
  ghVerdictMain: { fontSize: 16, fontWeight: '900', letterSpacing: 0.5 },
  ghVerdictSub: { fontSize: 8, color: C.dim, marginTop: 6, lineHeight: 14, fontWeight: '500' },
  ghHistWrap: { marginTop: 14 },
  ghQuote: {
    marginTop: 22,
    padding: 18,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(201,168,76,0.15)',
    backgroundColor: 'rgba(0,0,0,0.35)',
  },
  ghQuoteMark: { fontSize: 28, color: 'rgba(201,168,76,0.2)', lineHeight: 28, marginBottom: -8, fontFamily: Platform.select({ ios: 'Georgia', android: 'serif', default: 'serif' }) },
  ghQuoteTxt: {
    fontSize: 11,
    color: C.text,
    lineHeight: 18,
    fontStyle: 'italic',
    fontWeight: '500',
    letterSpacing: 0.3,
  },
  ghQuoteSig: { marginTop: 12, fontSize: 8, color: C.goldD, fontWeight: '800', letterSpacing: 2 },

  pnl: { backgroundColor: C.panel, borderWidth: 1, borderColor: C.border, borderRadius: DR.panel, overflow: 'hidden' },
  gmPanelShell: { borderColor: 'rgba(201,168,76,0.25)' },
  gmHeaderTint: { backgroundColor: 'rgba(201,168,76,0.05)' },
  srPanelShell: { borderColor: 'rgba(255,61,87,0.3)' },
  srHeadTint: { backgroundColor: 'rgba(255,61,87,0.04)' },
  flipShell: { borderColor: 'rgba(255,179,0,0.3)' },
  flipHeadTint: { backgroundColor: 'rgba(255,179,0,0.04)' },
  scanShell: { borderColor: 'rgba(64,196,255,0.3)' },
  scanHeadTint: { backgroundColor: 'rgba(64,196,255,0.04)' },

  ph: {
    paddingVertical: 10,
    paddingHorizontal: 13,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
    justifyContent: 'space-between',
    backgroundColor: 'rgba(201,168,76,0.02)',
  },
  phT: { fontSize: 9, fontWeight: '800', color: C.gold, letterSpacing: 2, textTransform: 'uppercase' },
  phB: {
    fontSize: 6,
    color: C.dim,
    letterSpacing: 1,
    borderWidth: 1,
    borderColor: C.border,
    paddingVertical: 2,
    paddingHorizontal: 6,
    borderRadius: DR.chip,
    fontWeight: '600',
  },
  histRangeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    paddingHorizontal: 13,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
    backgroundColor: 'rgba(201,168,76,0.02)',
  },
  histRangeChip: {
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: DR.chip,
    paddingVertical: 4,
    paddingHorizontal: 8,
    backgroundColor: 'rgba(0,0,0,0.2)',
  },
  histRangeChipOn: {
    borderColor: C.gold,
    backgroundColor: 'rgba(212,180,90,0.18)',
  },
  histRangeChipTxt: {
    fontSize: 6,
    letterSpacing: 0.8,
    fontWeight: '700',
    color: C.dim,
  },
  histRangeChipTxtOn: {
    color: C.goldL,
  },
  histEmpty: {
    paddingVertical: 16,
    paddingHorizontal: 12,
    fontSize: 10,
    color: C.dim,
    textAlign: 'center',
  },
  pb: { paddingHorizontal: 13, paddingVertical: 11 },

  biasHero: { alignItems: 'center', paddingVertical: 12 },
  biasTag: { fontSize: 7, color: C.dim, letterSpacing: 2, marginBottom: 4 },
  biasWord: { fontSize: 26, fontWeight: '800', letterSpacing: 4 },
  biasBull: { color: C.green },
  biasBear: { color: C.red },
  biasNeu: { color: C.dim },
  biasSub: { fontSize: 7, color: C.dim, marginTop: 2 },
  tfRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 5,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(30,23,0,0.5)',
  },
  tfl: { fontSize: 8, color: C.dim, fontWeight: '600' },
  tfv: { fontSize: 8, fontWeight: '700' },
  tfBull: { color: C.green },
  tfBear: { color: C.red },
  tfNeu: { color: C.amber },

  geoDial: { alignItems: 'center', paddingVertical: 12 },
  geoRiskLbl: { fontSize: 7, color: C.dim, letterSpacing: 2, marginBottom: 5 },
  geoLevel: { fontSize: 24, fontWeight: '900', letterSpacing: 3, color: C.red },
  geoSub: { fontSize: 7, color: C.dim, letterSpacing: 1, marginTop: 3 },
  geoBars: { gap: 4, marginVertical: 10 },
  geoBar: { height: 20, width: 18, borderRadius: DR.mini, borderWidth: 1, borderColor: C.border },
  geoBarG: { backgroundColor: C.green },
  geoBarA: { backgroundColor: C.amber },
  geoBarR: { backgroundColor: C.red },
  geoRule: { fontSize: 8, color: C.red, letterSpacing: 0.5, textAlign: 'center', lineHeight: 14 },

  sectionLbl: {
    fontSize: 7,
    fontWeight: '700',
    color: C.dim,
    letterSpacing: 2,
    textTransform: 'uppercase',
    marginBottom: 6,
  },
  twoCol: { flexDirection: 'row', gap: 6, marginBottom: 8 },
  immedResBox: {
    flex: 1,
    backgroundColor: 'rgba(255,61,87,0.07)',
    borderWidth: 2,
    borderColor: 'rgba(255,61,87,0.4)',
    borderRadius: DR.block,
    padding: 10,
  },
  immedSupBox: {
    flex: 1,
    backgroundColor: 'rgba(0,230,118,0.07)',
    borderWidth: 2,
    borderColor: 'rgba(0,230,118,0.4)',
    borderRadius: DR.block,
    padding: 10,
  },
  imLbl: { fontSize: 7, color: C.dim, fontWeight: '700', letterSpacing: 1, marginBottom: 3 },
  imResVal: { fontSize: 18, fontWeight: '800', color: C.red },
  imSupVal: { fontSize: 18, fontWeight: '800', color: C.green },
  imSmall: { fontSize: 7, color: C.dim, marginTop: 2 },
  imDistRes: { fontSize: 8, fontWeight: '700', color: C.red, marginTop: 3 },
  imDistSup: { fontSize: 8, fontWeight: '700', color: C.green, marginTop: 3 },
  currPriceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 6,
    paddingHorizontal: 10,
    backgroundColor: 'rgba(64,196,255,0.05)',
    borderWidth: 1,
    borderColor: 'rgba(64,196,255,0.2)',
    borderRadius: DR.block,
    marginBottom: 8,
    gap: 6,
  },
  currLbl: { fontSize: 8, fontWeight: '700', color: C.blue },
  currVal: { fontSize: 14, fontWeight: '800', color: C.goldL },
  currPos: { fontSize: 8, fontWeight: '600', color: C.blue },
  poiResBox: {
    flex: 1,
    backgroundColor: 'rgba(255,61,87,0.04)',
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: 'rgba(255,61,87,0.3)',
    borderRadius: DR.block,
    padding: 10,
  },
  poiSupBox: {
    flex: 1,
    backgroundColor: 'rgba(0,230,118,0.04)',
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: 'rgba(0,230,118,0.3)',
    borderRadius: DR.block,
    padding: 10,
  },
  poiResVal: { fontSize: 15, fontWeight: '800', color: 'rgba(255,61,87,0.7)' },
  poiSupVal: { fontSize: 15, fontWeight: '800', color: 'rgba(0,230,118,0.7)' },

  flipSupOuter: {
    marginBottom: 8,
    paddingVertical: 9,
    paddingHorizontal: 11,
    backgroundColor: 'rgba(0,230,118,0.06)',
    borderWidth: 1,
    borderColor: 'rgba(0,230,118,0.3)',
    borderRadius: DR.block,
    overflow: 'hidden',
    position: 'relative',
  },
  flipAccentGreen: { position: 'absolute', left: 0, top: 0, bottom: 0, width: 3, backgroundColor: C.green },
  flipGreenLbl: { fontSize: 7, color: C.green, fontWeight: '700', letterSpacing: 1.5, marginBottom: 4 },
  flipSupLvl: { fontSize: 18, fontWeight: '800', color: C.green },
  miniTagG: {
    fontSize: 7,
    fontWeight: '700',
    paddingVertical: 2,
    paddingHorizontal: 7,
    borderRadius: DR.chip,
    backgroundColor: 'rgba(0,230,118,0.1)',
    borderWidth: 1,
    borderColor: 'rgba(0,230,118,0.3)',
    color: C.green,
  },
  miniTagG2: {
    fontSize: 7,
    fontWeight: '700',
    paddingVertical: 2,
    paddingHorizontal: 7,
    borderRadius: DR.chip,
    backgroundColor: 'rgba(0,230,118,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(0,230,118,0.2)',
    color: C.green,
  },
  flipResOuter: {
    marginBottom: 8,
    paddingVertical: 9,
    paddingHorizontal: 11,
    backgroundColor: 'rgba(255,61,87,0.04)',
    borderWidth: 1,
    borderColor: 'rgba(255,61,87,0.2)',
    borderRadius: DR.block,
    overflow: 'hidden',
    position: 'relative',
  },
  flipAccentRed: { position: 'absolute', left: 0, top: 0, bottom: 0, width: 3, backgroundColor: 'rgba(255,61,87,0.3)' },
  flipDimLbl: { fontSize: 7, color: C.dim, fontWeight: '700', letterSpacing: 1.5, marginBottom: 4 },
  flipResLvl: { fontSize: 18, fontWeight: '800', color: 'rgba(255,61,87,0.5)' },
  miniTagWatch: {
    alignSelf: 'flex-start',
    fontSize: 7,
    fontWeight: '700',
    paddingVertical: 2,
    paddingHorizontal: 7,
    borderRadius: DR.chip,
    backgroundColor: 'rgba(255,61,87,0.06)',
    borderWidth: 1,
    borderColor: 'rgba(255,61,87,0.15)',
    color: C.dim,
  },
  flipRuleBox: {
    paddingVertical: 7,
    paddingHorizontal: 10,
    backgroundColor: 'rgba(255,179,0,0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255,179,0,0.2)',
    borderRadius: DR.block,
  },
  flipRuleTxt: { fontSize: 7, color: C.amber, lineHeight: 14, fontWeight: '600' },

  pathLblG: { fontSize: 7, fontWeight: '700', color: C.green, letterSpacing: 1.5, textTransform: 'uppercase', marginBottom: 5 },
  pathLblR: { fontSize: 7, fontWeight: '700', color: C.red, letterSpacing: 1.5, textTransform: 'uppercase', marginBottom: 5 },
  lsPanel: {
    backgroundColor: 'rgba(0,0,0,0.2)',
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: DR.block,
    overflow: 'hidden',
  },
  lsZoneBox: {
    marginHorizontal: 8,
    marginTop: 8,
    marginBottom: 4,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: DR.block,
    borderWidth: 2,
    justifyContent: 'center',
  },
  lsZonePath: {
    fontSize: 7,
    fontWeight: '800',
    letterSpacing: 1.2,
    color: C.dim,
    textTransform: 'uppercase',
  },
  lsZonePips: { fontSize: 22, fontWeight: '900', marginTop: 4 },
  lsZoneChop: { fontSize: 9, fontWeight: '700', color: C.text, marginTop: 6, opacity: 0.92 },
  lsZoneStatus: { fontSize: 10, fontWeight: '900', marginTop: 8, letterSpacing: 0.5 },
  lsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
  },
  lsRowL: { fontSize: 8, fontWeight: '600', color: C.dim },
  lsRowR: { fontSize: 8, fontWeight: '800' },
  pathVerdict: { marginTop: 4, paddingVertical: 6, paddingHorizontal: 8, borderRadius: DR.block, borderWidth: 1 },
  lsVerdictBox: { paddingVertical: 10, paddingHorizontal: 12, borderRadius: DR.block, borderWidth: 1, alignItems: 'center', marginTop: 8 },
  lsVerdictLbl: { fontSize: 7, fontWeight: '700', letterSpacing: 2, marginBottom: 3 },
  lsVerdictVal: { fontSize: 14, fontWeight: '800' },
  lsVerdictSub: { fontSize: 7, color: C.dim, marginTop: 3 },

  dxyRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(30,23,0,0.4)',
  },
  dxyL: { fontSize: 8, color: C.dim, fontWeight: '500' },
  dxyV: { fontSize: 8, fontWeight: '600' },
  dxyFoot: {
    marginTop: 8,
    paddingVertical: 6,
    paddingHorizontal: 8,
    backgroundColor: C.greenD,
    borderWidth: 1,
    borderColor: 'rgba(0,230,118,0.15)',
    borderRadius: DR.block,
    fontSize: 7,
    color: C.green,
    letterSpacing: 0.5,
  },

  chopActive: {
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: DR.block,
    alignItems: 'center',
    marginBottom: 10,
    backgroundColor: 'rgba(255,179,0,0.06)',
    borderWidth: 1,
    borderColor: 'rgba(255,179,0,0.25)',
  },
  chopWord: { fontSize: 16, fontWeight: '800', letterSpacing: 2 },
  chopSub: { fontSize: 7, marginTop: 3, letterSpacing: 1 },

  athZone: {
    backgroundColor: 'rgba(255,61,87,0.04)',
    borderWidth: 1,
    borderColor: 'rgba(255,61,87,0.2)',
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: DR.block,
    marginBottom: 8,
  },
  athTitle: { fontSize: 8, color: C.red, letterSpacing: 1.5, marginBottom: 6, fontWeight: '700' },
  athRange: { fontSize: 15, fontWeight: '800', color: C.red },
  athSub: { fontSize: 7, color: C.dim, marginTop: 2 },

  sigCard: {
    borderWidth: 1,
    borderColor: C.goldD,
    backgroundColor: '#16130E',
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderRadius: DR.block,
    overflow: 'hidden',
    position: 'relative',
  },
  sigCardCompact: {
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderRadius: DR.block,
  },
  sigInnerStack: { gap: 12 },
  sigTopTrade: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  tradeSigHeader: {
    flexDirection: 'row',
    alignItems: 'stretch',
    justifyContent: 'space-between',
    gap: 10,
  },
  tradeSigSideBadge: {
    flex: 1,
    minWidth: 0,
    borderRadius: DR.soft,
    borderWidth: 1,
    paddingVertical: 12,
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  tradeSigSideTxt: { fontSize: 28, fontWeight: '800', letterSpacing: 2, lineHeight: 32 },
  tradeSigSideSub: { fontSize: 8, color: C.dim, letterSpacing: 1.2, fontWeight: '700', textAlign: 'center' },
  tradeSigSessChip: {
    borderRadius: DR.soft,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: 'rgba(0,0,0,0.28)',
    paddingVertical: 10,
    paddingHorizontal: 12,
    justifyContent: 'center',
    alignItems: 'center',
    maxWidth: 120,
  },
  tradeSigSessLbl: { fontSize: 7, color: C.dim, letterSpacing: 1.2, fontWeight: '700', marginBottom: 4 },
  tradeSigSessTxt: { fontSize: 9, color: C.text, fontWeight: '700', textAlign: 'center', lineHeight: 13 },
  tradeSigPair: { fontSize: 9, color: C.dim, letterSpacing: 1.8, fontWeight: '700' },
  tradeSigPill: { alignSelf: 'stretch', textAlign: 'center', marginTop: 2 },
  tradeSigSetupRow: { flexDirection: 'row', gap: 8 },
  tradeSetupChip: {
    flex: 1,
    borderRadius: DR.chip,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: 'rgba(0,0,0,0.22)',
    paddingVertical: 8,
    paddingHorizontal: 6,
    alignItems: 'center',
    gap: 3,
  },
  tradeSetupChipLive: {
    borderColor: 'rgba(0,230,118,0.45)',
    backgroundColor: 'rgba(0,230,118,0.08)',
  },
  tradeSetupChipLbl: { fontSize: 8, color: C.dim, fontWeight: '800', letterSpacing: 1 },
  tradeSetupChipVal: { fontSize: 10, fontWeight: '800', letterSpacing: 0.5 },
  tradeSigEngineBox: {
    borderRadius: DR.soft,
    borderWidth: 1,
    borderColor: 'rgba(201,168,76,0.22)',
    backgroundColor: 'rgba(0,0,0,0.2)',
    paddingVertical: 10,
    paddingHorizontal: 12,
    gap: 6,
  },
  tradeSigConfRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 8 },
  tradeSigConfLbl: { fontSize: 8, color: C.gold, fontWeight: '700', letterSpacing: 0.8, flex: 1 },
  tradeSigConfPct: { fontSize: 13, fontWeight: '800', color: C.goldL },
  tradeSigReason: { fontSize: 9, color: C.text, lineHeight: 14, fontWeight: '500' },
  tradeSigWick: { fontSize: 8, color: C.dim, lineHeight: 13, fontStyle: 'italic' },
  sigBuyBadge: {
    width: 72,
    minHeight: 88,
    borderRadius: DR.chip,
    borderWidth: 1,
    borderColor: 'rgba(0,230,118,0.35)',
    backgroundColor: 'rgba(0,230,118,0.06)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
  },
  sigActionCompact: { fontSize: 26, lineHeight: 30, letterSpacing: 1 },
  sigInfoCompact: { flex: 1, minWidth: 0, gap: 6 },
  sigPairCompact: { fontSize: 9, color: C.dim, letterSpacing: 1.5, fontWeight: '700' },
  sigConfCompact: { fontSize: 10, color: C.gold, fontWeight: '700', lineHeight: 15 },
  sigStratCompact: { fontSize: 8, color: C.dim, letterSpacing: 0.3, lineHeight: 14, fontWeight: '500' },
  sigSessCompact: {
    fontSize: 8,
    color: C.dim,
    letterSpacing: 0.8,
    textAlign: 'center',
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: DR.chip,
    backgroundColor: 'rgba(0,0,0,0.25)',
    borderWidth: 1,
    borderColor: C.border,
    overflow: 'hidden',
  },
  sigBtnRow: { flexDirection: 'row', alignItems: 'stretch', gap: 10, marginTop: 2 },
  execBtnCompact: {
    flex: 1,
    paddingVertical: 14,
    paddingHorizontal: 10,
    borderRadius: DR.soft,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 50,
  },
  execBtnTxtCompact: { color: '#000', fontSize: 11, fontWeight: '800', letterSpacing: 1.5 },
  skipBtnCompact: {
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: DR.soft,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 50,
    minWidth: 100,
  },
  skipBtnTxtCompact: { color: C.red, fontSize: 10, fontWeight: '700', letterSpacing: 1 },
  sigWatermarkCompact: { opacity: 0.06, top: '36%' },
  sigGlow: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'transparent',
    opacity: 1,
  },
  sigAccent: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: 4,
    backgroundColor: C.green,
    borderTopLeftRadius: DR.block,
    borderBottomLeftRadius: DR.block,
  },
  sigInner: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'stretch',
    gap: 12,
    flexWrap: 'nowrap',
  },
  sigL: { flex: 1, minWidth: 0, gap: 14, alignItems: 'center', flexDirection: 'row' },
  sigAction: { fontSize: 36, fontWeight: '800', lineHeight: 40 },
  sigBuy: { color: C.green },
  sigInfo: { flex: 1, minWidth: 0, gap: 4 },
  sigPair: { fontSize: 8, color: C.dim, letterSpacing: 2, fontWeight: '600' },
  pillWick: {
    alignSelf: 'flex-start',
    fontSize: 8,
    paddingVertical: 3,
    paddingHorizontal: 10,
    borderRadius: DR.chip,
    letterSpacing: 1,
    marginBottom: 2,
    fontWeight: '700',
    color: C.red,
    borderWidth: 1,
    borderColor: 'rgba(255,61,87,0.4)',
    backgroundColor: 'rgba(255,61,87,0.06)',
  },
  pillBreak: {
    alignSelf: 'flex-start',
    fontSize: 8,
    paddingVertical: 3,
    paddingHorizontal: 10,
    borderRadius: DR.chip,
    color: C.blue,
    borderWidth: 1,
    borderColor: 'rgba(64,196,255,0.4)',
    backgroundColor: 'rgba(64,196,255,0.06)',
    fontWeight: '700',
  },
  pillFlip: {
    alignSelf: 'flex-start',
    fontSize: 8,
    paddingVertical: 3,
    paddingHorizontal: 10,
    borderRadius: DR.chip,
    color: C.amber,
    borderWidth: 1,
    borderColor: 'rgba(255,179,0,0.4)',
    backgroundColor: 'rgba(255,179,0,0.06)',
    fontWeight: '700',
  },
  sigConf: { fontSize: 10, color: C.gold, fontWeight: '700' },
  sigStrat: { fontSize: 7, color: C.dim, letterSpacing: 0.5 },
  sigR: { flexShrink: 0, alignItems: 'flex-end', justifyContent: 'center', gap: 6 },
  sigSess: { fontSize: 7, color: C.dim, letterSpacing: 1, textAlign: 'right' },
  execBtn: {
    backgroundColor: C.gold,
    paddingVertical: 10,
    paddingHorizontal: 22,
    borderRadius: DR.soft,
  },
  execBtnTxt: { color: '#000', fontSize: 9, fontWeight: '800', letterSpacing: 2 },
  skipBtn: {
    borderWidth: 1,
    borderColor: 'rgba(255,61,87,0.3)',
    paddingVertical: 6,
    paddingHorizontal: 14,
    borderRadius: DR.soft,
    backgroundColor: 'transparent',
  },
  skipBtnTxt: { color: C.red, fontSize: 8, fontWeight: '600', letterSpacing: 1 },
  sigWatermark: {
    position: 'absolute',
    right: -18,
    top: '42%',
    fontSize: 7,
    color: 'rgba(201,168,76,0.12)',
    letterSpacing: 4,
    transform: [{ rotate: '90deg' }],
    fontWeight: '700',
  },

  filterGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginBottom: 8 },
  filt: { flexGrow: 1, flexBasis: '22%', paddingVertical: 8, paddingHorizontal: 10, borderRadius: DR.soft, gap: 3, minWidth: '22%' },
  filtOk: { backgroundColor: C.greenD, borderWidth: 1, borderColor: 'rgba(0,230,118,0.2)' },
  filtWarn: { backgroundColor: C.redD, borderWidth: 1, borderColor: 'rgba(255,61,87,0.2)' },
  filtAmb: { backgroundColor: 'rgba(255,179,0,0.06)', borderWidth: 1, borderColor: 'rgba(255,179,0,0.2)' },
  filtL: { fontSize: 7, color: C.dim, letterSpacing: 1, fontWeight: '600' },
  filtV: { fontSize: 13, fontWeight: '800' },
  filtS: { fontSize: 7, letterSpacing: 0.5, fontWeight: '600' },

  wickInd: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 8,
    paddingHorizontal: 11,
    borderRadius: DR.block,
    marginBottom: 8,
    backgroundColor: C.greenD,
    borderWidth: 1,
    borderColor: 'rgba(0,230,118,0.2)',
  },
  wiIcon: { fontSize: 16 },
  wiMain: { fontSize: 8, color: C.text, letterSpacing: 0.5, marginBottom: 1, fontWeight: '600' },
  wiSub: { fontSize: 7, color: C.dim },

  atrRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 6 },
  atrLabel: { fontSize: 8, color: C.dim, fontWeight: '600' },
  atrVal: { fontSize: 14, fontWeight: '800', color: C.amber },
  atrBarBg: { height: 5, backgroundColor: 'rgba(255,255,255,0.05)', borderRadius: DR.mini, overflow: 'hidden', marginBottom: 10 },
  atrBarFill: { height: '100%', borderRadius: DR.mini, backgroundColor: C.amber },
  modePill: {
    alignSelf: 'flex-start',
    fontSize: 8,
    paddingVertical: 3,
    paddingHorizontal: 10,
    borderRadius: DR.chip,
    letterSpacing: 1,
    marginBottom: 10,
    fontWeight: '700',
  },
  modeStd: { color: C.green, borderWidth: 1, borderColor: 'rgba(0,230,118,0.3)', backgroundColor: C.greenD },
  modeAmb: { color: C.amber, borderWidth: 1, borderColor: 'rgba(255,179,0,0.3)', backgroundColor: 'rgba(255,179,0,0.06)' },
  modeRed: { color: C.red, borderWidth: 1, borderColor: 'rgba(255,61,87,0.3)', backgroundColor: C.redD },

  eeGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 7, marginBottom: 8 },
  eeCell: {
    flexGrow: 1,
    flexBasis: '22%',
    backgroundColor: 'rgba(0,0,0,0.3)',
    borderWidth: 1,
    borderColor: C.border,
    padding: 10,
    borderRadius: DR.block,
    minWidth: '45%',
  },
  eeL: { fontSize: 6, color: C.dim, letterSpacing: 1.5, textTransform: 'uppercase', marginBottom: 4, fontWeight: '700' },
  eeV: { fontSize: 15, fontWeight: '800' },
  eeS: { fontSize: 7, color: C.dim, marginTop: 2 },
  eeEntry: { color: C.green },
  eeBe: { color: C.purple },
  eeTp1: { color: C.goldL },
  eeTp2: { color: C.gold },
  eeSl: { color: C.red },
  eePlain: { color: C.text },
  eeGold: { color: C.gold },

  rrStrip: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 8,
    backgroundColor: 'rgba(201,168,76,0.04)',
    borderWidth: 1,
    borderColor: C.border,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: DR.block,
  },
  rri: { alignItems: 'center', minWidth: '18%' },
  rrl: { fontSize: 6, color: C.dim, letterSpacing: 1, fontWeight: '600' },
  rrv: { fontSize: 13, fontWeight: '800', color: C.gold },

  chartWrap: {
    height: 120,
    backgroundColor: 'rgba(0,0,0,0.2)',
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: DR.block,
    overflow: 'hidden',
    position: 'relative',
  },
  chartAth: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    height: 10,
    backgroundColor: 'rgba(255,61,87,0.06)',
    borderTopLeftRadius: DR.block,
    borderTopRightRadius: DR.block,
  },
  chartAthTxt: {
    position: 'absolute',
    left: 4,
    top: 1,
    fontSize: 6,
    color: 'rgba(255,61,87,0.6)',
  },
  chartDot: {
    position: 'absolute',
    width: 3,
    height: 3,
    borderRadius: 1.5,
    backgroundColor: C.gold,
    marginLeft: -1.5,
    marginTop: -1.5,
  },
  hLine: {
    position: 'absolute',
    left: 0,
    right: 0,
    borderTopWidth: 1,
    borderStyle: 'dashed',
    borderColor: 'rgba(216,200,144,0.35)',
  },
  hLineLbl: { position: 'absolute', top: -10, fontSize: 6 },
  vLine: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    borderLeftWidth: 1,
    borderStyle: 'dashed',
    borderColor: 'rgba(0,230,118,0.45)',
  },
  vLineLbl: { position: 'absolute', left: 4, top: 4, fontSize: 6 },
  wickGrab: {
    position: 'absolute',
    left: '49%',
    top: '52%',
    width: '8%',
    height: '24%',
    backgroundColor: 'rgba(255,61,87,0.07)',
    borderWidth: 1,
    borderColor: 'rgba(255,61,87,0.35)',
    borderRadius: DR.chip,
  },
  wickGrabLbl: { position: 'absolute', left: '48%', bottom: 4, fontSize: 7, color: C.red },

  histTableWrap: {
    borderRadius: DR.block,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(30,23,0,0.45)',
    backgroundColor: 'rgba(0,0,0,0.2)',
  },
  histHead: {
    flexDirection: 'row',
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
    gap: 4,
    alignItems: 'flex-start',
  },
  histTh: { fontSize: 6, color: C.dim, letterSpacing: 1, fontWeight: '700', textTransform: 'uppercase' },
  histColUtc: { flex: 0.7, minWidth: 0 },
  histColDir: { flex: 0.4, minWidth: 0 },
  histColType: {
    flex: 0.9,
    minWidth: 0,
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingTop: 1,
  },
  histColEntry: { flex: 1, minWidth: 0, flexShrink: 1, paddingRight: 2 },
  histColSl: { flex: 0.8, minWidth: 0 },
  histColBe: { flex: 0.8, minWidth: 0 },
  histColPl: { flex: 0.9, minWidth: 0 },
  histColRes: { flex: 0.7, minWidth: 0 },
  histBreakMsg: { color: C.red, fontSize: 7, lineHeight: 11, fontWeight: '600' },
  histDashCell: { color: C.dim2, fontSize: 7, textAlign: 'center' },
  histRow: {
    flexDirection: 'row',
    paddingHorizontal: 8,
    paddingVertical: 7,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(30,23,0,0.4)',
    alignItems: 'flex-start',
    gap: 4,
  },
  histTd: { fontSize: 8, fontWeight: '500', color: C.text },
  tBuy: { color: C.green, fontWeight: '800' },
  tSell: { color: C.red, fontWeight: '800' },
  tWin: { color: C.green, fontWeight: '600' },
  tLoss: { color: C.red, fontWeight: '600' },
  tOpen: { color: C.gold, fontWeight: '600' },
  eb: { fontSize: 6, paddingVertical: 1, paddingHorizontal: 5, borderRadius: DR.mini, fontWeight: '700', overflow: 'hidden' },
  ebW: { backgroundColor: 'rgba(255,61,87,0.1)', color: C.red },
  ebB: { backgroundColor: 'rgba(64,196,255,0.1)', color: C.blue },
  ebF: { backgroundColor: 'rgba(255,179,0,0.1)', color: C.amber },

  pnlHero: { alignItems: 'center', paddingVertical: 14 },
  pnlTag: { fontSize: 7, color: C.dim, letterSpacing: 2, marginBottom: 5, fontWeight: '600' },
  pnlNum: { fontSize: 32, fontWeight: '800' },
  pnlPips: { fontSize: 8, color: C.dim, marginTop: 3 },
  pnlMini: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 },
  pmC: {
    flexGrow: 1,
    flexBasis: '45%',
    backgroundColor: 'rgba(0,0,0,0.3)',
    borderWidth: 1,
    borderColor: C.border,
    padding: 8,
    borderRadius: DR.block,
    alignItems: 'center',
  },
  pmL: { fontSize: 7, color: C.dim, letterSpacing: 1, marginBottom: 3, fontWeight: '600' },
  pmV: { fontSize: 15, fontWeight: '800', color: C.gold },

  rmHdr: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 4 },
  rmL: { fontSize: 7, color: C.dim, fontWeight: '600' },
  rmV: { fontSize: 7, color: C.green, fontWeight: '600' },
  rmBar: { height: 4, backgroundColor: 'rgba(255,255,255,0.04)', borderRadius: DR.mini, overflow: 'hidden', marginBottom: 10 },
  rmFill: { height: '100%', borderRadius: DR.mini, backgroundColor: C.gold },

  yieldPct: { fontSize: 14, fontWeight: '900', color: C.purple },
  yieldBarBg: { height: 6, backgroundColor: 'rgba(255,255,255,0.04)', borderRadius: DR.mini, overflow: 'hidden', marginBottom: 6 },
  yieldFill: { height: '100%', borderRadius: DR.mini, backgroundColor: C.purple },
  yieldMarkers: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8 },
  yieldMk: { fontSize: 7, color: C.dim, fontWeight: '500' },

  dayCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: 10,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: 'rgba(0,0,0,0.2)',
    borderRadius: DR.block,
    marginBottom: 8,
  },
  dayIcon: { fontSize: 20 },
  dayName: { fontSize: 13, fontWeight: '800', color: C.gold },
  dayMode: { fontSize: 7, color: C.dim, letterSpacing: 1, marginTop: 2 },
  dayRule: { fontSize: 8, color: C.green, marginTop: 3, fontWeight: '600' },

  spreadGuard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 8,
    paddingHorizontal: 11,
    borderRadius: DR.block,
    marginBottom: 8,
  },
  sgOk: { backgroundColor: C.greenD, borderWidth: 1, borderColor: 'rgba(0,230,118,0.2)' },
  sgWarn: { backgroundColor: C.redD, borderWidth: 1, borderColor: 'rgba(255,61,87,0.25)' },
  sgLabel: { fontSize: 7, color: C.dim, letterSpacing: 1, marginBottom: 2, fontWeight: '600' },
  sgSpread: { fontSize: 20, fontWeight: '800' },
  sgTiny: { fontSize: 7, color: C.dim },
  sgTiny2: { fontSize: 7, color: C.dim, marginTop: 2 },
  sgStatus: { fontSize: 8, letterSpacing: 1 },

  newsClear: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    backgroundColor: C.greenD,
    borderWidth: 1,
    borderColor: 'rgba(0,230,118,0.2)',
    borderRadius: DR.block,
    fontSize: 7,
    color: C.green,
    letterSpacing: 1,
    marginBottom: 7,
    textAlign: 'center',
    fontWeight: '700',
  },
  ni: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 5,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(30,23,0,0.4)',
    gap: 6,
  },
  niTime: { fontSize: 8, color: C.dim, fontWeight: '500', minWidth: 36 },
  niName: { flex: 1, fontSize: 8, color: C.text, fontWeight: '500' },
  niImpact: { fontSize: 6, paddingVertical: 2, paddingHorizontal: 6, borderRadius: DR.mini, letterSpacing: 1, fontWeight: '700' },
  niH: { color: C.red, borderWidth: 1, borderColor: 'rgba(255,61,87,0.3)', backgroundColor: 'rgba(255,61,87,0.05)' },
  niM: { color: C.amber, borderWidth: 1, borderColor: 'rgba(255,179,0,0.3)', backgroundColor: 'rgba(255,179,0,0.05)' },
  niOk: { fontSize: 6, color: C.green, fontWeight: '700' },
  niPast: { fontSize: 6, color: C.dim, fontWeight: '500' },
  niBlock: { fontSize: 6, color: C.red, letterSpacing: 1, fontWeight: '700' },
  newsFoot: {
    marginTop: 7,
    paddingTop: 7,
    borderTopWidth: 1,
    borderTopColor: C.border,
    fontSize: 7,
    color: C.dim,
    lineHeight: 14,
  },
  });
}
